name: Verify renovate offers

on:
  pull_request:
    branches:    
      - main
      - 'renovate/**'

jobs:
  build:
    name: build but no push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tomfankhaenel/route53-dyndns
      - name: Build Docker image
        uses: docker/build-push-action@v5.4.0
        with:
          context: src
          file: src/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ env.GITHUB_REF_NAME }}
